x = float(input('Введите координату X'))
y = float(input('Введите координату Y'))
z = float(input('Введите координату Z'))
vlength = ((x) ** (2) + (y) ** (2) + (z) ** (2)) ** (0.5)
print(vlength) 